[[main]]
  identifier = "posts"
  name = "文章列表"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "漫画"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "摄影"
  url = "gallery/photo"

[[main]]
  identifier = "showcase"
  name = "项目展示"
  url = "showcase"
  weight = 4

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 5