[[main]]
  identifier = "公众号文章"
  name = "公众号文章"
  url = "公众号文章"
  weight = 1

[[main]]
  identifier = "归档"
  name = "归档"
  url = "归档"
  weight = 2

[[main]]
  identifier = "showcase"
  name = "项目展示"
  url = "showcase"
  weight = 3

[[main]]
  identifier = "收藏夹"
  name = "收藏夹"
  url = "收藏夹"
  weight = 4

[[main]]
  identifier = "关于"
  name = "关于"
  url = "关于"
  weight = 4