
[[main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[main]]
  identifier = "posts"
  name = "文章列表"
  url = "posts"
  weight = 2

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "leoay"
  url = "gallery/mine"

[[main]]
  identifier = "showcase"
  name = "项目合集"
  url = "showcase"
  weight = 5

  [[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 6