[[main]]
  identifier = "关于"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "归档"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "图集"
  name = "图集"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "图集"
  name = "leoay"
  url = "gallery/mine"

[[main]]
  identifier = "文章列表"
  name = "文章列表"
  url = "posts"
  weight = 4