[[main]]
  identifier = "posts"
  name = "文章列表"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "showcase"
  name = "项目展示"
  url = "showcase"
  weight = 3

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4