[en]
  title = "Hugo Zzo Theme"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[cn]
  title = "Hugo Zzo Theme"
  languageName = "中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/cn"
